services:
  api-minecraftrcon-nodejs:
    container_name: api-minecraftrcon-nodejs
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: "host"
    restart: unless-stopped
    environment:
      - HOST=localhost
      - PORT=3000
      - RCON_HOST=localhost
      - RCON_PORT=25575
      - RCON_PASSWORD=root
